Megyek/Megyek/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Megyek.Pages
{
    public class AboutModel : PageModel
    {
        public string Message1 { get; set; }
        public string Message2 { get; set; }

        public void OnGet()
        {
            Message1 = "This app is for sports teams.";
            Message2 = "Allows team members to indicate their willingness to attend each event with a single click.";
        }
    }
}

Megyek/Megyek/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Megyek.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Megyek.eu contact page.";
        }
    }
}

Megyek/Megyek/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Megyek.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Megyek/Megyek/Pages/EventCreate.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Megyek.Models;

namespace Megyek.Pages.Event
{
    public class CreateModel : PageModel
    {
        private readonly IEventRepo repo;
        private readonly IMeProvider meProvider;
        public Models.Team Team;

        public CreateModel(IEventRepo repo, IMeProvider meProvider)
        {
            this.repo = repo;
            this.meProvider = meProvider;
        }

        public void OnGet(int? teamId)
        {
            Team = meProvider.GetManagedTeam(teamId);
        }

        [BindProperty]
        public Megyek.Models.Event Event { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await repo.CreateEventAsync(Event);

            return RedirectToPage("EventIndex", new { teamId = Event?.TeamId });
        }
    }
}

Megyek/Megyek/Pages/EventDelete.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Megyek.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Megyek.Pages.Event
{
    public class DeleteModel : PageModel
    {
        private readonly IEventRepo repo;
        public DeleteModel(IEventRepo repo)
        {
            this.repo = repo;
        }

        [BindProperty]
        public Megyek.Models.Event Event { get; set; }

        public void OnGet(int? id)
        {
            Event = repo.GetManagedEvent(id);
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await repo.DeleteEventAsync(id);
            return RedirectToPage("EventIndex", new { teamId = Event?.TeamId });
        }
    }
}

Megyek/Megyek/Pages/EventDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Megyek.Models;

namespace Megyek.Pages.Event
{
    public class DetailsModel : PageModel
    {
        private readonly IEventRepo repo;
        public DetailsModel(IEventRepo repo)
        {
            this.repo = repo;
        }

        public Megyek.Models.Event Event { get; set; }

        public void OnGet(int? id)
        {
            Event = repo.GetManagedEvent(id);
        }
    }
}

Megyek/Megyek/Pages/EventEdit.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Megyek.Models;

namespace Megyek.Pages.Event
{
    public class EditModel : PageModel
    {
        private readonly IEventRepo repo;
        public EditModel(IEventRepo repo)
        {
            this.repo = repo;
        }

        [BindProperty]
        public Megyek.Models.Event Event { get; set; }

        public void OnGet(int? id)
        {
            Event = repo.GetManagedEvent(id);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                await repo.SaveEventAsync(Event);
            }
            catch (DbUpdateConcurrencyException)
            {
                Models.Event x = await repo.GetEventAsync(Event.Id);
                if (x == null)
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToPage("EventIndex", new { teamId = Event?.TeamId });
        }
    }
}

Megyek/Megyek/Pages/EventIndex.cshtml.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Megyek.Models;

namespace Megyek.Pages.Event
{
    public class IndexModel : PageModel
    {
        private readonly IEventRepo repo;
        private readonly IMeProvider meProvider;
        public Models.Team Team;

        public IndexModel(IEventRepo repo, IMeProvider meProvider)
        {
            this.repo = repo;
            this.meProvider = meProvider;
        }

        public IList<Megyek.Models.Event> Event { get;set; }

        public void OnGet(int? teamId)
        {
            Team = meProvider.GetManagedTeam(teamId);
            Event = repo.GetEventList(Team?.Id);
        }
    }
}

Megyek/Megyek/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Megyek.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Megyek.Pages
{
    public class IndexModel : PageModel
    {
        //private MegyekDbContext dbContext;
        private readonly IMeProvider meProvider;
        private readonly IEventRepo eventRepo;
        private readonly IMembershipRepo membershipRepo;
        private readonly IParticipationRepo participationRepo;
        private readonly IParticipationTextProvider participationTextProvider;
        private readonly IPostRepo postRepo;
        private readonly IMailService mailService;

        public Person Me;
        public IList<Team> MyTeams;
        public Team Team;
        public Models.Event Event;
        public IList<Models.Event> NextEvents;
        public IList<Models.Event> SpecialEvents;
        public Models.Membership Membership;
        public Participation Participation;

        public bool? Participate { get { return Participation?.Participate; } }
        public int GoingCount { get { return Event?.Participation?.Count(x => x.Participate ?? false) ?? 0; } }
        public int SkippingCount { get { return Event?.Participation?.Count(x => !(x.Participate ?? true)) ?? 0; } }

        public IList<Models.Post> Posts;
        public Models.Post MyLastPost;

        public IndexModel
            (IMeProvider meProvider
            , IEventRepo eventRepo
            , IMembershipRepo membershipRepo
            , IParticipationRepo participationRepo
            , IParticipationTextProvider participationTextProvider
            , IPostRepo postRepo
            , IMailService mailService
            )
        {
            //this.dbContext = dbContext;
            this.meProvider = meProvider;
            this.eventRepo = eventRepo;
            this.membershipRepo = membershipRepo;
            this.participationRepo = participationRepo;
            this.participationTextProvider = participationTextProvider;
            this.postRepo = postRepo;
            this.mailService = mailService;
        }

        public async Task OnGetAsync(int? teamId, int? eventId)
        {
            await LoadContextAsync(teamId, eventId);
        }

        private async Task LoadContextAsync(int? teamId, int? eventId)
        {
            Me = meProvider.Me;
            MyTeams = Me.Membership.Select(x => x.Team).ToList() ?? new List<Team>();

            Event = await eventRepo.GetEventAsync(eventId);
            if (Event == null)
            {
                Team = meProvider.GetTeam(teamId);
                Event = Team?.Event.OrderBy(x => x.Date).FirstOrDefault(x => x.Date > DateTime.Now);
            }
            else
            {
                Team = meProvider.GetTeam(Event.TeamId);
                if (Team?.Id != Event.TeamId)
                {
                    Event = null;
                }
            }
            Membership = Me.Membership.FirstOrDefault(x => x.TeamId == Team?.Id);
            Participation = Event?.Participation.FirstOrDefault(x => x.PersonId == Me.Id);

            NextEvents = Team.Event
                .OrderBy(x => x.Date)
                .Where(x => !x.Special && x.Date > DateTime.Now.AddHours(-1) && x.Id != Event?.Id)
                .Take(5)
                .ToList();
            SpecialEvents = Team.Event
                .OrderBy(x => x.Date)
                .Where(x => x.Special && x.Date > DateTime.Now.AddHours(-1) && x.Id != Event?.Id)
                .ToList();

            Posts = Team.Post.TakeLast(50).OrderByDescending(x => x.Id).ToList();
            if (Posts.Count > 0 && Posts[0].PersonId == Me?.Id) MyLastPost = Posts[0];
        }

        public async Task<IActionResult> OnPostGoing(int? eventId, int? personId = null)
        {
            await Going(eventId, personId);
            return RedirectToPage("./Index", new { eventId });
        }
        public async Task OnGetGoing(int? eventId, int? personId = null)
        {
            await Going(eventId, personId);
            await LoadContextAsync(null, eventId);
        }
        public async Task Going(int? eventId, int? personId = null)
        {
            await LoadContextAsync(null, eventId);
            if (Event != null 
                && ((Membership?.Manager ?? false) || personId == null))
            {
                Participation participation = Event?.Participation.FirstOrDefault(x => x.PersonId == (personId ?? Me.Id));
                if (!(participation?.Participate ?? false))
                {
                    if (participation == default(Participation))
                    {
                        participation = new Participation()
                        {
                            PersonId = personId ?? Me.Id,
                            ByPersonId = Me.Id,
                            EventId = Event.Id,
                            Participate = true,
                            Date = DateTime.Now
                        };
                        await participationRepo.AddParticipationAsync(participation);
                    }
                    else
                    {
                        participation.ByPersonId = Me.Id;
                        participation.Participate = true;
                        participation.Date = DateTime.Now;
                        await participationRepo.SaveParticipationAsync(participation);
                    }
                    await mailService.SendParticipatonMailAsync(participation);
                }
            }
        }

        public async Task<IActionResult> OnPostSkipping(int? eventId, int? personId = null)
        {
            await Skipping(eventId, personId);
            return RedirectToPage("./Index", new { eventId });
        }
        public async Task OnGetSkipping(int? eventId, int? personId = null)
        {
            await Skipping(eventId, personId);
            await LoadContextAsync(null, eventId);
        }
        public async Task Skipping(int? eventId, int? personId = null)
        {
            await LoadContextAsync(null, eventId);
            if (Event != null
                && ((Membership?.Manager ?? false) || personId == null))
            { 
                Participation participation = Event?.Participation.FirstOrDefault(x => x.PersonId == (personId ?? Me.Id));
                if (participation?.Participate ?? true)
                {
                    if (participation == default(Participation))
                    {
                        participation = new Participation()
                        {
                            PersonId = personId ?? Me.Id,
                            ByPersonId = Me.Id,
                            EventId = Event.Id,
                            Participate = false,
                            Date = DateTime.Now
                        };
                        await participationRepo.AddParticipationAsync(participation);
                    }
                    else
                    {
                        participation.ByPersonId = Me.Id;
                        participation.Participate = false;
                        participation.Date = DateTime.Now;
                        await participationRepo.SaveParticipationAsync(participation);
                    }
                    await mailService.SendParticipatonMailAsync(participation);
                }
            }
        }

        public async Task<IActionResult> OnPostPostingAsync(string postText, int? teamId, int? eventId)
        {
            if (string.IsNullOrEmpty(postText)) return Page();
            await LoadContextAsync(teamId, eventId);
            if (Event == null) return Page();

            Models.Post post = new Models.Post()
            {
                TeamId = Event.TeamId,
                PersonId = Me.Id,
                Date = DateTime.Now,
                Text = postText
            };
            await postRepo.AddPostAsync(post);
            await mailService.SendPostMailAsync(post);
            return RedirectToPage("./Index", new { teamId, eventId });
        }

        public async Task<IActionResult> OnPostDeletePost(int? postId, int? teamId, int? eventId)
        {
            await LoadContextAsync(teamId, eventId);
            if (Event == null) return Page();

            Models.Post post = await postRepo.GetPostAsync(postId);
            if (post != null && post.PersonId == Me?.Id)
            {
                await postRepo.RemovePostAsync(post);
            }
            return RedirectToPage("./Index", new { teamId, eventId });
        }
        public async Task<IActionResult> OnPostMail(int? teamId, int? eventId)
        {
            await LoadContextAsync(teamId, eventId);
            await membershipRepo.SetMailAsync(this.Membership);
            return RedirectToPage("./Index", new { teamId, eventId });
        }

        public async Task<IActionResult> OnPostAlert(int? teamId, int? eventId)
        {
            await LoadContextAsync(teamId, eventId);
            if (Event == null) return Page();

            await mailService.SendAlertMailAsync(Event);
            return RedirectToPage("./Index", new { teamId, eventId });
        }

        public string GetParticipationDisplayNameX(Participation participation)
        {
            return participationTextProvider.GetPersonDisplayNameX(participation);
        }

        public string GetParticipationDisplayText()
        {
            return participationTextProvider.GetDisplayText(Participation);
        }

    }
}

Megyek/Megyek/Pages/MembershipCreate.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Megyek.Models;

namespace Megyek.Pages.Membership
{
    public class CreateModel : PageModel
    {
        private readonly IMembershipRepo repo;
        private readonly IMeProvider meProvider;

        public CreateModel(IMembershipRepo repo, IMeProvider meProvider)
        {
            this.repo = repo;
            this.meProvider = meProvider;
        }

        public void OnGet(int? teamId)
        {
            Team team = meProvider.GetManagedTeam(teamId);
            Membership = new Models.Membership()
            {
                Team = team,
                TeamId = team.Id,
                Person = new Person()
            };
        }

        [BindProperty]
        public Models.Membership Membership { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await repo.CreateMembershipAsync(Membership);

            return RedirectToPage("MembershipIndex", new { teamId = Membership?.TeamId } );
        }
    }
}

Megyek/Megyek/Pages/MembershipDelete.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Megyek.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Megyek.Pages.Membership
{
    public class DeleteModel : PageModel
    {
        private readonly IMembershipRepo repo;
        public DeleteModel(IMembershipRepo repo)
        {
            this.repo = repo;
        }

        [BindProperty]
        public Megyek.Models.Membership Membership { get; set; }

        public void OnGet(int? teamId, int? personId)
        {
            Membership = repo.GetManagedMembership(teamId, personId);
        }

        public async Task<IActionResult> OnPostAsync(int? teamId, int? personId)
        {
            if (teamId == null || personId == null)
            {
                return NotFound();
            }
            await repo.DeleteMembershipAsync(teamId, personId);
            return RedirectToPage("MembershipIndex", new { teamId = teamId });
        }
    }
}

Megyek/Megyek/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message1</h3>
<p>@Model.Message2</p>

Megyek/Megyek/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<!--
<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>
-->

<address>
    <strong>Support:</strong> <a href="mailto:Support@megyek.eu">Support@megyek.eu</a><br />
</address>

Megyek/Megyek/Pages/EventCreate.cshtml
@page
@model Megyek.Pages.Event.CreateModel

@{
    ViewData["Title"] = "Create new event";
}

<h2>Create</h2>
@if (Model.Team.Id > 0)
{
    <p>
        @Html.DisplayFor(model => Model.Team.Name)
    </p>

    <h4>Event</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Event.TeamId" value="@Model.Team.Id" />
                <div class="form-group">
                    <label asp-for="Event.Date" class="control-label"></label>
                    <input asp-for="Event.Date" class="form-control" />
                    <span asp-validation-for="Event.Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Event.Description" class="control-label"></label>
                    <input asp-for="Event.Description" class="form-control" />
                    <span asp-validation-for="Event.Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Event.Place" class="control-label"></label>
                    <input asp-for="Event.Place" class="form-control" value="@Model.Team.DefaultPlace"  />
                    <span asp-validation-for="Event.Place" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-page="EventIndex" asp-route-teamId="@Model.Team.Id">Back to List</a>
    </div>
}
else
{
    <b>No permission to any team!</b>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Megyek/Megyek/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Seleted event";
}
<style>
    #imagewithcaption {
        float: left;
        width: 52px;
        text-align: center;
        font-size: x-small;
    }

    table {
        width: 100%;
    }

    span.cyan {
        background-color: #b9edfb;
        padding: 3px;
        margin: 3px;
        line-height: 1.8;
    }

    span.pink {
        background-color: #f2cdcd;
        padding: 3px;
        margin: 3px;
        line-height: 1.8;
    }

    span.green {
        background-color: #a7e4c8;
        padding: 3px;
        margin: 3px;
        line-height: 1.8;
    }

    span.grey {
        background-color: #e0e0e0;
        padding: 3px;
        margin: 3px;
        line-height: 1.8;
    }
</style>
<hr>
@if (Model.Me.Id != 0)
{
<table>
    <tr>
        <td style="width:100px"><b>User :</b></td>
        <td>
            @if (!string.IsNullOrEmpty(Model.Membership?.DisplayName))
            {
                <span class="cyan">
                    @Html.DisplayFor(model => model.Membership.DisplayName)
                </span>
            }
        </td>
        <td style="width:100px">
            @if (!string.IsNullOrEmpty(Model.Membership?.DisplayName))
            {
                <form asp-page-handler="Mail" method="post">
                    Mail:
                    @if (Model.Membership.Mail)
                    {
                        <button class="btn btn-default" style="background-color: #a7e4c8; border:solid; border-width:1px;">On</button>
                    }
                    else
                    {
                        <button class="btn btn-default" style="background-color: #f2cdcd; border:solid; border-width:1px;">Off</button>
                    }
                    <input type="hidden" name="teamId" value="@Model.Team?.Id" />
                    <input type="hidden" name="eventId" value="@Model.Event?.Id" />
                </form>
            }
        </td>
    </tr>
    <tr>
        <td><b>Team :</b></td>
        <td>
            @if (!string.IsNullOrEmpty(Model.Team.Name))
            {
                <span class="cyan">
                    @Html.DisplayFor(model => model.Team.Name)
                </span>
            }
        </td>
        <td style="width:100px; align-content:center;">
            @if (Model.Membership?.Manager ?? false)
            {
                <a asp-page="EventIndex" asp-route-teamId="@Model.Team.Id"> Events </a>
                <a asp-page="MembershipIndex" asp-route-teamId="@Model.Team.Id"> Members </a>
            }
        </td>
    </tr>
    @if (Model.MyTeams.Count > 1)
    {
        <tr>
            <td colspan="3">
                @foreach (var item in Model.MyTeams)
                {
                    if (item.Id != Model.Team.Id)
                    {
                        <span class="grey">
                            <a asp-page="./Index" asp-route-teamId="@item.Id">@item.Name</a>
                        </span>
                    }
                }
            </td>
        </tr>
    }
</table>
}
else
{
<p>Please log in or register!</p>
}
@if (Model.Event != null)
{
    <hr>
    <table>
        <tr>
            <td style="width:100px"><b>Event :</b></td>
            <td>
                <span class="cyan">
                    @Model.Event.Description
                </span>
                <span class="cyan">
                    @Html.DisplayFor(model => model.Event.DisplayDate)
                </span>
                <span class="cyan">
                    @Html.DisplayFor(model => model.Event.Place)
                </span>
            </td>
        </tr>
        @if (Model.NextEvents.Count > 0)
        {
            <tr>
                <td colspan="2">
                    @foreach (var item in Model.NextEvents)
                    {
                        <span class="grey">
                            <a asp-page="./Index" asp-route-eventId="@item.Id">@item.Description</a>
                        </span>
                        @:
                    }
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    @foreach (var item in Model.SpecialEvents)
                    {
                        <span class="grey">
                            <a asp-page="./Index" asp-route-eventId="@item.Id">@item.Description</a>
                        </span>
                        @:
                    }
                </td>
            </tr>
        }
    </table>
    <hr>
    <table>
        <tr>
            <td style="width:100px;"><b>Going (@Html.DisplayFor(model => model.GoingCount)):</b></td>
            <td>
                @foreach (var item in Model.Event.Participation.OrderBy(x => x.Date))
                {
                    if (item.Participate ?? false)
                    {
                        <span class="green">
                            @if (Model.Membership?.Manager ?? false)
                            {
                                <a asp-page-handler="Skipping" method="post" asp-route-eventId="@Model.Event.Id" asp-route-personId="@item.PersonId">@Model.GetParticipationDisplayNameX(item)</a>
                            }
                            else
                            {
                                @Model.GetParticipationDisplayNameX(item)
                            }
                        </span>
                    }
                }
            </td>
        </tr>
        <tr>
            <td style="width:100px;"><b>Skipping (@Html.DisplayFor(model => model.SkippingCount)):</b></td>
            <td>
                @foreach (var item in Model.Event.Participation.OrderBy(x => x.Date))
                {
                    if (!(item.Participate ?? true))
                    {
                        <span class="pink">
                            @if (Model.Membership?.Manager ?? false)
                            {
                                <a asp-page-handler="Going" method="post" asp-route-eventId="@Model.Event.Id" asp-route-personId="@item.PersonId">@Model.GetParticipationDisplayNameX(item)</a>
                            }
                            else
                            {
                                @Model.GetParticipationDisplayNameX(item)
                            }
                        </span>
                    }
                }
            </td>
        </tr>
        <tr>
            <td style="width:100px;"><b>Unknown :</b></td>
            <td>
                @foreach (var item in Model.Team.Membership.Where(x => !Model.Event.Participation.Where(y => y.PersonId == x.PersonId).Any()))
                {
                    <span class="grey">
                        @if (Model.Membership?.Manager ?? false)
                        {
                            <a asp-page-handler="Going" method="post" asp-route-eventId="@Model.Event.Id" asp-route-personId="@item.PersonId">@item.DisplayNameX</a>
                        }
                        else
                        {
                            @item.DisplayNameX
                        }
                    </span>
                }
            </td>
        </tr>
    </table>
    <table>
        <tr>
            @if (!(Model.Participate ?? false))
            {
                <td style="width:100px;">
                    <form asp-page-handler="Going" method="post">
                        <button class="btn btn-default" style="background-color: #a7e4c8; border:solid; border-width:1px;">Going</button>
                        <input type="hidden" name="eventId" value="@Model.Event?.Id" />
                    </form>
                </td>
            }
            @if (Model.Participate ?? true)
            {
                <td style="width:100px;">
                    <form asp-page-handler="Skipping" method="post">
                        <button class="btn btn-default" style="background-color: #f2cdcd; border:solid; border-width:1px;">Skipping</button>
                        <input type="hidden" name="eventId" value="@Model.Event?.Id" />
                    </form>
                </td>
            }
            @if (Model.Participation != null)
            {
                <td>@Model.GetParticipationDisplayText()</td>
            }
            else
            {
                <td> </td>
            }
            <td style="width:100px">
                @if (Model.Event?.IsAlertAllowed ?? false)
                {
                    <form asp-page-handler="Alert" method="post">
                        Alert:<button class="btn btn-default" style="background-color: #a7e4c8; border:solid; border-width:1px;">Send</button>
                        <input type="hidden" name="teamId" value="@Model.Team?.Id" />
                        <input type="hidden" name="eventId" value="@Model.Event?.Id" />
                    </form>
                }
                else
                {
                    @Model.Event.LastAlertSentAsText;
                }
            </td>
        </tr>
    </table>
}
@if (Model.Team.Id != 0)
{
    <hr>
    <table>
        <tr>
            <td>
                <form asp-page-handler="Posting" method="post" style="display: flex; align-items: center">
                    <button class="btn btn-default">+</button>
                    <textarea name="postText" cols="40" rows="3" maxlength="4000" style="resize: none;"></textarea>
                    <input type="hidden" name="teamId" value="@Model.Team?.Id" />
                    <input type="hidden" name="eventId" value="@Model.Event?.Id" />
                </form>
            </td>
        </tr>
    </table>
    <table class="table-striped">
        @foreach (var item in Model.Posts)
        {
            <tr>
                <td style="width:160px">
                    <b>@Html.DisplayFor(modelItem => item.DisplayName)</b>
                    <br>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                @if (item.Id == Model.MyLastPost?.Id)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Text)
                    </td>
                    <td style="width:50px">
                        <form asp-page-handler="DeletePost" method="post">
                            <button class="btn btn-default">X</button>
                            <input type="hidden" name="postId" value="@item.Id" />
                            <input type="hidden" name="teamId" value="@Model.Team?.Id" />
                            <input type="hidden" name="eventId" value="@Model.Event?.Id" />
                        </form>
                    </td>
                }
                else
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Text)
                    </td>
                }
            </tr>
        }
    </table>
    @if (Model.Posts.Count >= 50)
    {
        <hr>
        <a asp-page="PostIndex" asp-route-teamId="@Model.Team.Id">Full post history</a>
    }
}